export const LOOKUP_SYMBOL = "LOOKUP_SYMBOL";
export const LOOKUP_SYMBOL_SUCCESS = "LOOKUP_SYMBOL_SUCCESS";
export const LOOKUP_SYMBOL_ERROR = "LOOKUP_SYMBOL_ERROR";

export const BUY_STOCK = "BUY_STOCK";
export const BUY_STOCK_SUCCESS = "BUY_STOCK_SUCCESS";
export const BUY_STOCK_ERROR = "BUY_STOCK_ERROR";

export const SELL_STOCK = "SELL_STOCK";
export const SELL_STOCK_SUCCESS = "SELL_STOCK_SUCCESS";
export const SELL_STOCK_ERROR = "SELL_STOCK_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";
